version: '3'
services:
  node:
    image: jjcb/orbis-training-docker:2.0.0
    ports:
      - "1042:1042"
      - "35729:35729"
    working_dir: /app
    volumes:
      - .:/app
    command: npm start